# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.cauldron_boil_particle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
# Dependency Versions
modJavaVersion=17
# Minecraft Versions
minecraftVersion=1.20.1
minecraftVersionRange=[1.20.1,1.20.2]
# Forge Versions
neoforgeVersion=47.1.65
neoforgeVersionRange=[47,)
loaderVersionRange=[4.10,)
# Mappings
# | Channel   | Version              |                                                                                |
# |-----------|----------------------|--------------------------------------------------------------------------------|
# | official  | MCVersion            | Official field/method names from Mojang mapping files                          |
# | parchment | YYYY.MM.DD-MCVersion | Open community-sourced parameter names and javadocs layered on top of official |
parchmentChannel=parchment
# The mapping version to query from the mapping channel.
# This must match the format required by the mapping channel.
parchmentVersion=2023.09.03-1.20.1
# Build Dependencies Versions
mixinVersion=0.8.5
# Mod Properties
modName=Hexerei
modId=hexerei
modVersion=0.4.2.3
modLicense=MIT
modGroupId=net.joefoxe.hexerei
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
modAuthors=JoeFoxe
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
modDescription=Magic/Exploration/Storage Mod
# Mod Dependency Versions
jeiVersion=15.20.0.105
registrateVersion=MC1.20-1.3.3
# Other Optional Dependencies
arsNouveauVersion=4.9.0.165
curiosVersion=5.11.0+1.20.1
cyanideVersion=4824162
terraBlenderVersion=4590487